services:
  synthezia:
    image: ghcr.io/rishikanthc/synthezia:latest
    ports:
      - "8080:8080"
    volumes:
      - synthezia_data:/app/data
    restart: unless-stopped

volumes:
  synthezia_data:

